name: CMS Staging

on:
  push:
    branches:
      - main
    paths:
      - "cms/**"
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: cms

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out codes
        uses: actions/checkout@v2

      - name: Installing dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: 'npm'
      - run: npm install

      - name: Testing
        run: npm test

      - name: Deploy to app engine
        if: ${{ github.event_name != 'pull_request' }}
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: false

      - run: npm run deploy
        if: ${{ github.event_name != 'pull_request' }}
        env:
          NODE_ENV: production
          DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
