# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CMS Staging Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out codes
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
    
      - name: Installing yarn
        uses: actions/setup-node@v2
      - run: npm install -g yarn

      - name: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --skip-builds

      - name: Deploy to app engine
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: false
      - run: yarn cms:deploy
        env:
          NODE_ENV: production
          DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}